---
- name: Add Plex repository key
  ansible.builtin.apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present
  register: status_plex_repo

- name: Configure Plex repository
  ansible.builtin.apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb public main
    state: present
    update_cache: false
  register: status_plex_repo

- name: Install Plex Server
  ansible.builtin.apt:
    name: plexmediaserver
    state: present
    update_cache: "{{ status_plex_repo.changed }}"

- name: Start and enable Plex service
  ansible.builtin.service:
    name: plexmediaserver
    state: started
    enabled: true
